services:
  juststreamit_api:
      container_name: juststreamit_api
      # Docker stays up in background
      tty: true

      volumes:
        # Sharing APP folder from Host to Docker
        - type: bind
          source: ./app
          target: /home/user/app

      # Share network Stack host to docker
      # Priviledge mode => Not safe for production
      network_mode: host

      build:
        context: .
        dockerfile: Dockerfile
